### PR TITLE
Fixed bug #35: memory leak in OnigStringContext

### PR DESCRIPTION
**Pull request by ceejbot**
Added a destructor that resets the Persistent to free the memory used for it. The `leaks.js` repro script that @soldair provided shows the heapUsed staying where it's expected.

### CODE REVIEW

**Comment by soldair** [comment]
confirmed this fixes #35

**Comment by izuzak** [comment]
cc @kevinsawicki @zcbenz for :eyes:

**Comment by soldair** [comment]
failed to build on node 0.10.40 
```
../src/onig-string-context.cc: In destructor ‘OnigStringContext::~OnigStringContext()’:
../src/onig-string-context.cc:24:14: error: ‘class v8::Persistent<v8::String>’ has no member named ‘Reset’
     v8String.Reset();
              ^
```

File: src/onig-string-context.cc [hunk 1]
```diff
@@ -19,3 +19,7 @@ OnigStringContext::OnigStringContext(Handle<String> str)
 bool OnigStringContext::IsSame(Handle<String> other) const {
   return v8String == other;
 }
+
+OnigStringContext::~OnigStringContext() {
+    v8String.Reset();
```
Comment (zcbenz) [inline src/onig-string-context.cc]: We can use `Nan::Global` instead of `Persistent`, and `Nan::Global` calls `Reset` in its destructor so we won't need to call it here anymore.

**Comment by zcbenz** [comment]
Awesome, thanks!
